apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          # image: jenkins/jenkins:lts
          image: hyunjun1325/myjenkins:0.7
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: docker-socket
              mountPath: /var/run/
      initContainers:
        - name: init-docker-sock
          image: busybox
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["sh", "-c", "chmod 777 /var/run/docker.sock"]
          volumeMounts:
          - mountPath: /var/run
            name: docker-socket
            readOnly: false
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-claim
        - name: docker-socket
          hostPath:
            # directory location on host
            path: /var/run
            # this field is optional
            type: Directory